// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as React from "@testing-library/react";

function queryByLabelText(text) {
  return Primitive_option.fromNullable(React.screen.queryByLabelText(text));
}

function queryByLabelTextRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByLabelText(re));
}

function queryByLabelTextWith(text, opts) {
  return Primitive_option.fromNullable(React.screen.queryByLabelText(text, opts));
}

function queryByPlaceholderText(text) {
  return Primitive_option.fromNullable(React.screen.queryByPlaceholderText(text));
}

function queryByPlaceholderTextRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByPlaceholderText(re));
}

function queryByPlaceholderTextWith(text, opts) {
  return Primitive_option.fromNullable(React.screen.queryByPlaceholderText(text, opts));
}

function queryByText(text) {
  return Primitive_option.fromNullable(React.screen.queryByText(text));
}

function queryByTextRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByText(re));
}

function queryByTextWith(text, opts) {
  return Primitive_option.fromNullable(React.screen.queryByText(text, opts));
}

function queryByAltText(text) {
  return Primitive_option.fromNullable(React.screen.queryByAltText(text));
}

function queryByAltTextRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByAltText(re));
}

function queryByAltTextWith(text, opts) {
  return Primitive_option.fromNullable(React.screen.queryByAltText(text, opts));
}

function queryByTitle(text) {
  return Primitive_option.fromNullable(React.screen.queryByTitle(text));
}

function queryByTitleRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByTitle(re));
}

function queryByTitleWith(text, opts) {
  return Primitive_option.fromNullable(React.screen.queryByTitle(text, opts));
}

function queryByDisplayValue(value) {
  return Primitive_option.fromNullable(React.screen.queryByDisplayValue(value));
}

function queryByDisplayValueRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByDisplayValue(re));
}

function queryByDisplayValueWith(value, opts) {
  return Primitive_option.fromNullable(React.screen.queryByDisplayValue(value, opts));
}

function queryByRole(role) {
  return Primitive_option.fromNullable(React.screen.queryByRole(role));
}

function queryByRoleWith(role, opts) {
  return Primitive_option.fromNullable(React.screen.queryByRole(role, opts));
}

function queryByRoleWithRegex(role, opts) {
  return Primitive_option.fromNullable(React.screen.queryByRole(role, opts));
}

function queryByTestId(id) {
  return Primitive_option.fromNullable(React.screen.queryByTestId(id));
}

function queryByTestIdRegex(re) {
  return Primitive_option.fromNullable(React.screen.queryByTestId(re));
}

function queryByTestIdWith(id, opts) {
  return Primitive_option.fromNullable(React.screen.queryByTestId(id, opts));
}

function withinQueryByText(scope, text) {
  return Primitive_option.fromNullable(scope.queryByText(text));
}

export {
  queryByLabelText,
  queryByLabelTextRegex,
  queryByLabelTextWith,
  queryByPlaceholderText,
  queryByPlaceholderTextRegex,
  queryByPlaceholderTextWith,
  queryByText,
  queryByTextRegex,
  queryByTextWith,
  queryByAltText,
  queryByAltTextRegex,
  queryByAltTextWith,
  queryByTitle,
  queryByTitleRegex,
  queryByTitleWith,
  queryByDisplayValue,
  queryByDisplayValueRegex,
  queryByDisplayValueWith,
  queryByRole,
  queryByRoleWith,
  queryByRoleWithRegex,
  queryByTestId,
  queryByTestIdRegex,
  queryByTestIdWith,
  withinQueryByText,
}
/* @testing-library/react Not a pure module */
