// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(() => 0);
  let setCount = match[1];
  let match$1 = React.useState(() => "");
  let setName = match$1[1];
  let name = match$1[0];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "ReScript + Vite + React",
        className: "title",
        "data-testid": "app-heading"
      }),
      JsxRuntime.jsx("button", {
        children: `count is ` + match[0].toString(),
        onClick: param => setCount(count => count + 1 | 0)
      }),
      JsxRuntime.jsx("button", {
        children: "Reset",
        onClick: param => setCount(param => 0)
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("label", {
            children: "Name",
            htmlFor: "name-input"
          }),
          JsxRuntime.jsx("input", {
            id: "name-input",
            placeholder: "Type your name",
            value: name,
            onChange: e => setName(param => e.target.value)
          }),
          JsxRuntime.jsx("p", {
            children: `Hello, ` + name
          })
        ]
      }),
      JsxRuntime.jsx("button", {
        children: "Submit",
        disabled: name.trim() === ""
      }),
      JsxRuntime.jsx("p", {
        children: "Edit src/demo/App.res and save to test Fast Refresh."
      })
    ]
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
