// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";
import * as App$RescriptVitestBindings from "./App.res.mjs";
import * as TestingLibrary$RescriptVitestBindings from "../bindings/TestingLibrary.res.mjs";

Vitest.afterEach(prim => {
  React.cleanup();
});

Vitest.describe("App", () => {
  Vitest.test("renders the heading", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let heading = React.screen.getByText("ReScript + Vite + React");
    Vitest.expect(heading).toBeInTheDocument();
    Vitest.expect(heading).toBeVisible();
    Vitest.expect(heading).toHaveClass("title");
    Vitest.expect(heading).toHaveTextContent(/Vite/);
  });
  Vitest.test("finds elements by test id, role, and placeholder", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(React.screen.getByTestId("app-heading")).toBeInTheDocument();
    Vitest.expect(React.screen.getByRole("heading")).toHaveTextContent("ReScript + Vite + React");
    Vitest.expect(React.screen.getByRole("textbox")).toBeInTheDocument();
    Vitest.expect(React.screen.getByLabelText("Name")).toBeInTheDocument();
    Vitest.expect(React.screen.getByPlaceholderText("Type your name")).toBeInTheDocument();
    Vitest.expect(React.screen.getAllByRole("button").length).toBe(3);
  });
  Vitest.test("counter increments on click", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let button = React.screen.getByText("count is 0");
    React.fireEvent.click(button);
    Vitest.expect(React.screen.getByText("count is 1")).toBeInTheDocument();
    React.fireEvent.click(React.screen.getByText("count is 1"));
    Vitest.expect(React.screen.getByText("count is 2")).toBeInTheDocument();
  });
  Vitest.test("reset zeroes the counter", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    React.fireEvent.click(React.screen.getByText("count is 0"));
    React.fireEvent.click(React.screen.getByText("Reset"));
    Vitest.expect(React.screen.getByText("count is 0")).toBeInTheDocument();
  });
  Vitest.test("typing in the input updates the greeting", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let input = React.screen.getByLabelText("Name");
    React.fireEvent.change(input, {
      target: {
        value: "Ada"
      }
    });
    Vitest.expect(input).toHaveValue("Ada");
    Vitest.expect(React.screen.getByText("Hello, Ada")).toBeInTheDocument();
  });
  Vitest.test("submit button is disabled, counter is enabled", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(React.screen.getByText("Submit")).toBeDisabled();
    Vitest.expect(React.screen.getByText("count is 0")).toBeEnabled();
  });
  Vitest.test("submit enables after typing", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(React.screen.getByText("Submit")).toBeVisible();
    React.fireEvent.change(React.screen.getByLabelText("Name"), {
      target: {
        value: "Ada"
      }
    });
    Vitest.expect(React.screen.getByText("Submit")).toBeEnabled();
  });
  Vitest.test("finds buttons by role with accessible-name options", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(React.screen.getByRole("button", {
      name: "Reset"
    })).toBeInTheDocument();
    Vitest.expect(React.screen.getByRole("button", {
      name: /Reset/
    })).toBeInTheDocument();
    Vitest.expect(React.screen.getAllByRole("button", {
      name: "Reset"
    }).length).toBe(1);
    Vitest.expect(Stdlib_Option.isNone(TestingLibrary$RescriptVitestBindings.queryByRoleWith("button", {
      name: "no-such-button"
    }))).toBe(true);
  });
  Vitest.test("finds text by regex and exact options", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(React.screen.getByText(/count is/)).toBeInTheDocument();
    Vitest.expect(React.screen.getByText("count is 0", {
      exact: true
    })).toBeInTheDocument();
    Vitest.expect(React.screen.queryAllByText("count is 0").length).toBe(1);
    Vitest.expect(React.screen.queryAllByRole("button").length).toBe(3);
  });
  Vitest.test("queryBy wrappers return options", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    Vitest.expect(Stdlib_Option.isSome(TestingLibrary$RescriptVitestBindings.queryByText("count is 0"))).toBe(true);
    Vitest.expect(Stdlib_Option.isNone(TestingLibrary$RescriptVitestBindings.queryByText("nope-not-here"))).toBe(true);
    Vitest.expect(Stdlib_Option.isSome(TestingLibrary$RescriptVitestBindings.queryByTestId("app-heading"))).toBe(true);
    Vitest.expect(Stdlib_Option.isSome(TestingLibrary$RescriptVitestBindings.queryByLabelText("Name"))).toBe(true);
  });
  Vitest.test("findBy resolves for synchronously rendered UI", async () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let button = await React.screen.findByText("count is 0");
    Vitest.expect(button).toBeInTheDocument();
    let buttons = await React.screen.findAllByRole("button");
    Vitest.expect(buttons.length).toBe(3);
    let heading = await React.screen.findByRole("heading", {
      level: 1
    });
    Vitest.expect(heading).toHaveTextContent("ReScript + Vite + React");
  });
  Vitest.test("focus and blur update focus state", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let input = React.screen.getByLabelText("Name");
    input.focus();
    Vitest.expect(input).toHaveFocus();
    input.blur();
    Vitest.expect(input).not.toHaveFocus();
  });
  Vitest.test("jest-dom attribute and accessible matchers", () => {
    React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let input = React.screen.getByLabelText("Name");
    Vitest.expect(input).toHaveAttribute("placeholder");
    Vitest.expect(input).toHaveAttribute("placeholder", "Type your name");
    Vitest.expect(input).toHaveAccessibleName("Name");
    Vitest.expect(React.screen.getByTestId("app-heading")).toHaveRole("heading");
    Vitest.expect(React.screen.getByRole("textbox")).toHaveAccessibleName("Name");
  });
  Vitest.test("within scopes queries and input shows display value", () => {
    let result = React.render(JsxRuntime.jsx(App$RescriptVitestBindings.make, {}));
    let container = result.container;
    Vitest.expect(container).toContainElement(React.screen.getByText("count is 0"));
    Vitest.expect(React.within(container).getByText("Reset")).toBeInTheDocument();
    Vitest.expect(Stdlib_Option.isSome(TestingLibrary$RescriptVitestBindings.withinQueryByText(React.within(container), "count is 0"))).toBe(true);
    let input = React.screen.getByLabelText("Name");
    React.fireEvent.change(input, {
      target: {
        value: "Ada"
      }
    });
    Vitest.expect(input).toHaveDisplayValue("Ada");
    Vitest.expect(container).toContainAnyByText("Hello, Ada");
  });
});

/*  Not a pure module */
