// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as App$RescriptVitestBindings from "./demo/App.res.mjs";

let domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
    children: JsxRuntime.jsx(App$RescriptVitestBindings.make, {})
  }));
}

/* domElement Not a pure module */
